### ISSUE TITLE
STIV方法询问

### ISSUE THREAD

**Issue by yijizhiming** [wyxgoishin/test#4]
作者大大你好，我是一名研究生，目前正在研究视频测水速，我看你的STIV使用了BGT分权梯度算法，但是我用你的方法实验了一下，发现比起sobel算子计算角度，你的这个方法反而效果不太好。我看你的提交记录也是这样说的，请问你是从哪看的，这个方法是怎样的一个思路，恳请您能从百忙中回复一下，谢谢！

**Comment by wyxgoishin** [comment]
go to google scholar and search stiv
